### ISSUE TITLE
ckan-cloud-operator deis-instance create from-gcloud-envvars results in TypeError

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#1]
Trying to create an instance from gcloud envvars (with actual variables).

```
ckan-cloud-operator deis-instance create from-gcloud-envvars a b c d e f
```

This results in following:

```
Traceback (most recent call last):
  File "/opt/conda/envs/ckan-cloud-operator/bin/ckan-cloud-operator", line 11, in <module>
    load_entry_point('ckan-cloud-operator', 'console_scripts', 'ckan-cloud-operator')()
  File "/opt/conda/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: deis_instance_create_from_gcloud_envvars() got an unexpected keyword argument 'path_to_instance_env_yaml'
```

Looking at the code function awaits args, but it seems to be getting kwargs

```
@deis_instance_create.command('from-gcloud-envvars')
@click.argument('PATH_TO_INSTANCE_ENV_YAML')
@click.argument('IMAGE')
@click.argument('SOLR_CONFIG')
@click.argument('GCLOUD_DB_URL')
@click.argument('GCLOUD_DATASTORE_URL')
@click.argument('NEW_INSTANCE_ID')
def deis_instance_create_from_gcloud_envvars(*args):
    """Create and update an instance from existing DB dump stored in gcloud sql format on google cloud storage."""
    DeisCkanInstance.create('from-gcloud-envvars', *args).update()
    great_success()
```

an easy fix would be?

```
...
def deis_instance_create_from_gcloud_envvars(path_to_env, image, solr_conf, db_url, datastore_ur, instanc_id):
    """Create and update an instance from existing DB dump stored in gcloud sql format on google cloud storage."""
    DeisCkanInstance.create('from-gcloud-envvars', path_to_env, image, solr_conf, db_url, datastore_ur, instanc_id).update()
    great_success()

```

**Comment by OriHoch** [comment]
yes, your fix seem correct
