### ISSUE TITLE
Error: chart "ckan" matching version "v0.0.15-rc3" not found in ckan-cloud index. 

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#119]
This is not happening always, one may rerun and it might work fine. I've tried `helm repo update` but does not really change anything

Traceback
```
Error: chart "ckan" matching version "v0.0.15-rc3" not found in ckan-cloud index. (try 'helm repo update'). No chart version found for ckan-v0.0.15-rc3
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/ckan-cloud-operator", line 11, in <module>
    load_entry_point('ckan-cloud-operator', 'console_scripts', 'ckan-cloud-operator')()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/cli.py", line 34, in create
    wait_ready=wait_ready, skip_deployment=skip_deployment, skip_route=skip_route, force=force)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/manager.py", line 70, in create
    dry_run=dry_run)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/manager.py", line 104, in update
    deployment_manager.update(instance_id, instance_type, instance, force=force)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/deployment/manager.py", line 7, in update
    return _get_deployment_provider(instance_type).update(instance_id, instance, force=force, dry_run=dry_run)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/deployment/helm/manager.py", line 81, in update
    ckan_helm_release_name, instance_id, dry_run=dry_run
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/deployment/helm/manager.py", line 101, in _helm_deploy
    ckan_helm_release_name, f.name, instance_id, dry_run=dry_run)
  File "/home/travis/build/datopian/ckan-cloud-operator/ckan_cloud_operator/drivers/helm/driver.py", line 71, in deploy
    subprocess.check_call(f'{cmd} {dry_run_args}', shell=True)
  File "/opt/python/3.7.1/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'helm --tiller-namespace ckan-cloud-provider-ckan-deployment-helm upgrade ckan-cloud-a-ckan-instance ckan-cloud/ckan  --install --namespace "a-ckan-instance" -i --version "v0.0.15-rc3" -f /tmp/tmptsku_bee --dry-run --debug' returned non-zero exit status 1.
```

**Comment by zelima** [comment]
This seems to be happening when using old versions only Eg we have `v0.0.15-rc4` already and it's failing on `v0.0.15-rc3`. Still not expected behaviour I assume

**Comment by zelima** [comment]
INVALID or maybe FIXED. Probably that version was not actually pushed that time (maybe CD failed)
