### ISSUE TITLE
Instance create fails complaining about config values

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#85]
Tried to create an instance in minikube with cco (replicating this [script](https://github.com/datopian/ckan-cloud-operator/blob/master/scripts/create%20helm%20instance.py))
```
ckan-cloud-operator ckan instance create helm values.yaml --instance-id=second --instance-name=second --exists-ok --wait-ready --update
```

Where `values.yaml` looks like this (from https://github.com/ViderumGlobal/ckan-cloud-helm/blob/master/minikube-values.yaml, but fails as well with https://github.com/ViderumGlobal/ckan-cloud-helm/blob/master/aws-values.yaml). 
```
replicas: 1
nginxReplicas: 1
terminationGracePeriodSeconds: 1
datastoreDbTerminationGracePeriodSeconds: 1
dbTerminationGracePeriodSeconds: 1
ckanJobsTerminationGracePeriodSeconds: 1
ckanJobsDbTerminationGracePeriodSeconds: 1

# use the latest unstable version of the helm chart
ckanHelmChartVersion: v0.0.0
ckanHelmChartRepo: https://raw.githubusercontent.com/ViderumGlobal/ckan-cloud-helm/master/charts_repository
```

Getting assertion error:
```
2019-11-22 09:06 INFO (instance_id="second") Creating instance
Error from server (NotFound): configmaps "operator-conf" not found
Traceback (most recent call last):
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/bin/ckan-cloud-operator", line 11, in <module>
    load_entry_point('ckan-cloud-operator', 'console_scripts', 'ckan-cloud-operator')()
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/cli.py", line 34, in create
    wait_ready=wait_ready, skip_deployment=skip_deployment, skip_route=skip_route, force=force)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/manager.py", line 46, in create
    spec=values
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/crds/manager.py", line 108, in get_resource
    _, kind_suffix = _get_plural_kind_suffix(singular)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/crds/manager.py", line 210, in _get_plural_kind_suffix
    parts = config_manager.get(f'installed-crd-{singular}', required=True).split(',')
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/config/manager.py", line 21, in get
    assert value or not required, f'config value is required for {cache_key}:{key}'
AssertionError: config value is required for configmap:ckan-cloud:operator-conf:installed-crd-ckaninstance
```

**Comment by zelima** [comment]
One can create config map by running the following command
```
kubectl -n ckan-cloud create configmap operator-conf --from-literal=ckan-cloud-operator-image=viderum/ckan-cloud-operator:latest --from-literal=label-prefix=ckan-cloud
```

**Comment by zelima** [comment]
Actually this is not quite working as expected. Getting the same exact error after running
```
kubectl -n ckan-cloud create configmap operator-conf --from-literal=ckan-cloud-operator-image=viderum/ckan-cloud-operator:latest --from-literal=label-prefix=ckan-cloud
```

I can see operator-conf is there
```
kubectl get configmap -n ckan-cloud
NAME            DATA   AGE
operator-conf   2      21m
```

Probably worth to note that centralized infra is created following this instruction https://github.com/ViderumGlobal/ckan-cloud-helm/blob/master/QUICKSTART_DEVELOPMENT.md#optional-deploy-the-centralized-infrastructure and not by `ckan-cloud-operator cluster initialize` due to #87

**Comment by zelima** [comment]
Probably worth to note that centralized infra is created following this instruction https://github.com/ViderumGlobal/ckan-cloud-helm/blob/master/QUICKSTART_DEVELOPMENT.md#optional-deploy-the-centralized-infrastructure and not by `ckan-cloud-operator cluster initialize` due to #87

**Comment by zelima** [comment]
This seems to be a workaround - run as python script
```
from ckan_cloud_operator.providers.ckan.manager import *

crds_manager.initialize()
crds_manager.install_crd(INSTANCE_CRD_SINGULAR, INSTANCE_CRD_PLURAL_SUFFIX, INSTANCE_CRD_KIND_SUFFIX)
crds_manager.install_crd(INSTANCE_NAME_CRD_SINGULAR, INSTANCE_NAME_CRD_PLURAL_SUFFIX, INSTANCE_NAME_CRD_KIND_SUFFIX)
```

Passed the error above, but got to the new one (prob not related to this issue)

```
ckan-cloud-operator ckan instance create helm minikube-values.yaml --instance-id=second --instance-name=second --exists-ok --wait-ready --update
2019-11-26 11:22 INFO (instance_id="second") Creating instance
ckancloudckaninstance.stable.viderum.com/ckan-cloud-ckaninstance-second created
Error from server (NotFound): ckancloudckaninstancenames.stable.viderum.com "ckan-cloud-ckaninstancename-second" not found
ckancloudckaninstancename.stable.viderum.com/ckan-cloud-ckaninstancename-second created
Error from server (NotFound): namespaces "second" not found
2019-11-26 11:22 INFO creating instance namespace (second)
namespace/second created
serviceaccount/ckan-second-operator created
role.rbac.authorization.k8s.io/ckan-second-operator-role reconciled
	reconciliation required create
	missing rules added:
		{Verbs:[list get create] APIGroups:[*] Resources:[secrets pods pods/exec pods/portforward] ResourceNames:[] NonResourceURLs:[]}
rolebinding.rbac.authorization.k8s.io/ckan-second-operator-rolebinding reconciled
	reconciliation required create
	missing subjects added:
		{Kind:ServiceAccount APIGroup: Name:ckan-second-operator Namespace:second}
2019-11-26 11:22 WARNING Forcing centralized infra even though useCentralizedInfra is disabled
ckancloudckaninstance.stable.viderum.com/ckan-cloud-ckaninstance-second configured
Error from server (NotFound): configmaps "routers-config" not found
2019-11-26 11:22 WARNING forcing with_sans_ssl, even though withSansSSL is disabled
ckancloudckaninstance.stable.viderum.com/ckan-cloud-ckaninstance-second configured
2019-11-26 11:22 WARNING instance register sub domain was changed from None to ckan-cloud-second
ckancloudckaninstance.stable.viderum.com/ckan-cloud-ckaninstance-second configured
2019-11-26 11:22 WARNING instance siteUrl was changed from None to https://ckan-cloud-second.None
ckancloudckaninstance.stable.viderum.com/ckan-cloud-ckaninstance-second configured
Error from server (NotFound): secrets "ckan-admin-password" not found
2019-11-26 11:22 INFO (ckan_admin_email="admin@ckan-cloud-second.None") Will create new ckan admin user
Error from server (NotFound): secrets "ckan-admin-password" not found
secret/ckan-admin-password created
Error from server (NotFound): secrets "ckan-infra" not found
Traceback (most recent call last):
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/bin/ckan-cloud-operator", line 11, in <module>
    load_entry_point('ckan-cloud-operator', 'console_scripts', 'ckan-cloud-operator')()
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/cli.py", line 34, in create
    wait_ready=wait_ready, skip_deployment=skip_deployment, skip_route=skip_route, force=force)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/manager.py", line 52, in create
    dry_run=dry_run)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/manager.py", line 71, in update
    deployment_manager.update(instance_id, instance_type, instance, force=force)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/deployment/manager.py", line 2, in update
    return _get_deployment_provider(instance_type).update(instance_id, instance, force=force, dry_run=dry_run)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/deployment/helm/manager.py", line 53, in update
    _init_ckan_infra_secret(instance_id, dry_run=dry_run)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/deployment/helm/manager.py", line 232, in _init_ckan_infra_secret
    admin_user, admin_password, db_name = db_manager.get_admin_db_credentials()
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/db/manager.py", line 72, in get_admin_db_credentials
    db_provider_manager = get_provider()
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/db/manager.py", line 206, in get_provider
    return providers_manager.get_provider(db_provider_submodule)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/manager.py", line 10, in get_provider
    provider_id = get_provider_id(submodule, required=required)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/manager.py", line 63, in get_provider_id
    default=default
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/config/manager.py", line 21, in get
    assert value or not required, f'config value is required for {cache_key}:{key}'
AssertionError: config value is required for configmap:ckan-cloud:operator-conf:ckan-cloud-provider-db-main-provider-id
```

**Comment by zelima** [comment]
So, the error message from the previous command happens only once. If I try to rerun the same command now I'm getting different error message

```
ckan-cloud-operator ckan instance create helm minikube-values.yaml --instance-id=second --instance-name=second --exists-ok --wait-ready --update
2019-11-26 13:10 INFO (instance_id="second") Creating instance
The ckancloudckaninstances "ckan-cloud-ckaninstance-second" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
Traceback (most recent call last):
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/bin/ckan-cloud-operator", line 11, in <module>
    load_entry_point('ckan-cloud-operator', 'console_scripts', 'ckan-cloud-operator')()
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/cli.py", line 34, in create
    wait_ready=wait_ready, skip_deployment=skip_deployment, skip_route=skip_route, force=force)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/providers/ckan/instance/manager.py", line 47, in create
    ), dry_run=dry_run)
  File "/home/zelima/viderum/cco/ckan-cloud-operator/ckan_cloud_operator/kubectl.py", line 210, in apply
    input=yaml.dump(resource).encode(), shell=True, check=True
  File "/home/zelima/anaconda3/envs/ckan-cloud-operator/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'kubectl apply  -f -' returned non-zero exit status 1.
```

**Comment by zelima** [comment]
To summarize above + As discussed with @aluminiumgeek all 3 errors are caused by incorrect cluster initialization:

- Centralized infra is deployed via helm following https://github.com/ViderumGlobal/ckan-cloud-helm/blob/master/QUICKSTART_DEVELOPMENT.md#optional-deploy-the-centralized-infrastructure
- and not with `cloud-operator cluster initialize --interactive`
- Because of #87 - CCO is designed to work with DB as a separate instance on (GCloud SQL or AWS). It doesn't have the option to install SQL server inside the cluster

However, we can try running separate Postgresql instance locally and pass its IP and admin credentials on db provider initialization.

**Comment by aluminiumgeek** [comment]
Rather than *incorrect* cluster initialization, I'd say `cluster initialize` command for minikube clusters just not supported :)

> To summarize above + As discussed with @aluminiumgeek all 3 errors are caused by incorrect cluster initialization:
> 
> * Centralized infra is deployed via helm following https://github.com/ViderumGlobal/ckan-cloud-helm/blob/master/QUICKSTART_DEVELOPMENT.md#optional-deploy-the-centralized-infrastructure
> * and not with `cloud-operator cluster initialize --interactive`
> * Because of #87 - CCO is designed to work with DB as a separate instance on (GCloud SQL or AWS). It doesn't have the option to install SQL server inside the cluster
> 
> However, we can try running separate Postgresql instance locally and pass its IP and admin credentials on db provider initialization.

**Comment by akariv** [comment]
Can't we just spin a simple postgresql container in the cluster to act as a replacement for such cases?

**Comment by zelima** [comment]
@akariv we need to execute `cco cluster initialize` to avoid all those errors, but that command also takes care of database initializations and assumes one of `aws` or `gcloud` database instances should be initialized. 

This is how `db.initialize()` looks like atm https://github.com/datopian/ckan-cloud-operator/blob/master/ckan_cloud_operator/providers/db/manager.py#L15-L29 
```
def initialize(log_kwargs=None, interactive=False, default_cluster_provider=None):
    """Initialize / upgrade the db module and sub-modules"""
    if default_cluster_provider == 'aws':
        default_provider = db_rds_provider_id
    elif not default_cluster_provider or default_cluster_provider == 'gcloud':
        default_provider = db_gcloudsql_provider_id
    else:
        raise NotImplementedError(f'Unknown provider: {default_cluster_provider}')
```

> Can't we just spin a simple postgresql container in the cluster to act as a replacement for such cases?

Yes, we can extend and accept `minikube` as `default_cluster_provider` and spin a simple Postgres container if that is a case. I can start doing analysis as a part of #87 if you agree that is the way. to go

**Comment by zelima** [comment]
I've paster my findings here https://github.com/datopian/ckan-cloud-operator/issues/87

**Comment by pwalsh** [comment]
@zelima can this be closed?

**Comment by zelima** [comment]
Yes, none of above is happening now
